{% set name = "findspark" %}
{% set version = "1.4.1" %}
{% set bundle = "tar.gz" %}
{% set sha256 = "313a1c379e85c6085ccc7eaf9b86206884a8348a1053126c053db1a87f03cb06" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - findspark

about:
  home: https://github.com/minrk/findspark
  license_file: LICENSE.md
  license: BSD-3-clause
  license_family: BSD
  summary: Find pyspark to make it importable.
  dev_url: https://github.com/minrk/findspark

extra:
  recipe-maintainers:
    - mariusvniekerk
    - minrk
