{% set name = "findspark" %}
{% set version = "1.4.2" %}
{% set bundle = "tar.gz" %}
{% set sha256 = "6d52971f4417e976aea21aea0f4ac7e470fa365d6139100e03fb76b76eb97da0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - findspark

about:
  home: https://github.com/minrk/findspark
  license_file: LICENSE.md
  license: BSD 3-clause
  license_family: BSD
  summary: Find pyspark to make it importable.
  dev_url: https://github.com/minrk/findspark

extra:
  recipe-maintainers:
    - mariusvniekerk
    - minrk
